### ISSUE TITLE
Ask people to speak

### ISSUE THREAD

**Issue by andrewnl** [andrewnl/nlife#3]
- List of possible people
- Ask them!

**Comment by andrewfn** [comment]
I know that I need to ask them. Maybe tomorrow?

**Comment by andrewnl** [comment]
There could be a problem if gmail copies the thread all the time and it
builds up underneath?

On Sat, Mar 14, 2015 at 8:31 PM, Andrew Fountain notifications@github.com
wrote:

> I know that I need to ask them. Maybe tomorrow?
> 
> On Sat, Mar 14, 2015 at 6:30 PM, Andrew Fountain <notifications@github.com
> 
> > wrote:
> > 
> > Assigned #3 https://github.com/andrewnl/nlife/issues/3 to @andrewfn
> > https://github.com/andrewfn.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/andrewnl/nlife/issues/3#event-254059795.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andrewnl/nlife/issues/3#issuecomment-80773338.

## 

Andrew Fountain | New Life Church | nlife.ca | 416 515-7575
God's kingdom come in Toronto, demonstrating the love of the Father,
the truth of Jesus Christ, and the power of the Holy Spirit

**Comment by andrewfn** [comment]
Exactly!
Very messy!

**Comment by andrewfn** [comment]
Horrible new Gmail interface
