### ISSUE TITLE
Transition to Github: testing

### ISSUE THREAD

**Issue by andrewnl** [andrewnl/nlife#5]
For the testing phase we need to:
1. Create newlife user
- project: meetings
- add @andrewnl as administrator
- add as members: bumo luke-newlife ehibbert drichsmith annefn @andrewfn
1. Create initial test issue (public) for Apr 5, asking everyone to respond
   - with label & milestone.
2. Make sure we have signed everyone up and responding
3. Try to actually use it

**Comment by andrewnl** [comment]
More testing

**Comment by andrewfn** [comment]
how about you amf?

**Comment by andrewnl** [comment]
replying from amf

**Comment by andrewfn** [comment]
From a totally different account
