### ISSUE TITLE
Test if andrewfn can create a new issue

### ISSUE THREAD

**Issue by andrewfn** [andrewnl/nlife#6]
It seems that he can, and also mention another @writeup person!

**Comment by andrewfn** [comment]
It looks like the repo-owner (andrewnl) will automatically be copied on changes.

**Comment by andrewfn** [comment]
forgot to include @andrewfn myself

**Comment by andrewnl** [comment]
hi amf, can you?

**Comment by andrewfn** [comment]
Yes I can
